[2023-12-27 18:16:04,903] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: OpenWeather_ETL2.envio_mail manual__2023-12-27T18:15:41.747249+00:00 [queued]>
[2023-12-27 18:16:04,949] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: OpenWeather_ETL2.envio_mail manual__2023-12-27T18:15:41.747249+00:00 [queued]>
[2023-12-27 18:16:04,950] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-27 18:16:04,951] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-12-27 18:16:04,952] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-27 18:16:04,996] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): envio_mail> on 2023-12-27 18:15:41.747249+00:00
[2023-12-27 18:16:05,013] {standard_task_runner.py:52} INFO - Started process 14436 to run task
[2023-12-27 18:16:05,026] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'OpenWeather_ETL2', 'envio_mail', 'manual__2023-12-27T18:15:41.747249+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/ETL_OpenWeather2.py', '--cfg-path', '/tmp/tmpiulhmayi', '--error-file', '/tmp/tmp_c87l24_']
[2023-12-27 18:16:05,030] {standard_task_runner.py:80} INFO - Job 118: Subtask envio_mail
[2023-12-27 18:16:05,252] {task_command.py:371} INFO - Running <TaskInstance: OpenWeather_ETL2.envio_mail manual__2023-12-27T18:15:41.747249+00:00 [running]> on host 44a36bef83ad
[2023-12-27 18:16:05,635] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Furtado_Julio
AIRFLOW_CTX_DAG_ID=OpenWeather_ETL2
AIRFLOW_CTX_TASK_ID=envio_mail
AIRFLOW_CTX_EXECUTION_DATE=2023-12-27T18:15:41.747249+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-27T18:15:41.747249+00:00
[2023-12-27 18:16:07,601] {logging_mixin.py:115} INFO - 'ascii' codec can't encode character '\xe9' in position 62: ordinal not in range(128)
[2023-12-27 18:16:07,602] {logging_mixin.py:115} INFO - Error al enviar el correo
[2023-12-27 18:16:07,605] {python.py:173} INFO - Done. Returned value was: None
[2023-12-27 18:16:07,641] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=OpenWeather_ETL2, task_id=envio_mail, execution_date=20231227T181541, start_date=20231227T181604, end_date=20231227T181607
[2023-12-27 18:16:07,698] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-27 18:16:07,795] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
